version: "3"

services:
  redis-state:
    image: faasm/redis:${FAASM_VERSION}

  redis-queue:
    image: faasm/redis:${FAASM_VERSION}

  upload:
    image: faasm/upload:${FAASM_VERSION}
    ports:
      - "8002:8002"
    depends_on:
      - redis-queue
      - redis-state
    volumes:
      - ./build/:${FAASM_BUILD_MOUNT}/
      - ./wasm/:/usr/local/code/faasm/wasm/
      - ./container/machine-code/:/usr/local/faasm/object/
      - ./container/shared_store/:/usr/local/faasm/shared_store/
    environment:
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - PYTHON_CODEGEN=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib

  worker:
    image: faasm/worker:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
    privileged: yes
    volumes:
      - ./build/:${FAASM_BUILD_MOUNT}
    environment:
      - CAPTURE_STDOUT=on
      - CGROUP_MODE=on
      - FILESERVER_URL=http://${UPLOAD_HOST:-upload}:8002
      - FUNCTION_STORAGE=fileserver
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - MAX_IN_FLIGHT_RATIO=1
      - MAX_FAASLETS=20
      - MAX_FAASLETS_PER_FUNCTION=4
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib

  worker-storage:
    image: faasm/worker:${FAASM_VERSION}
    depends_on:
      - upload
    expose:
      - "8080"
    privileged: yes
    volumes:
      - ./build/:${FAASM_BUILD_MOUNT}
      - ./container/shared_store/:/usr/local/faasm/shared_store/
    environment:
      - CAPTURE_STDOUT=on
      - CGROUP_MODE=on
      - FILESERVER_URL=http://${UPLOAD_HOST:-upload}:8002
      - FUNCTION_STORAGE=fileserver
      - IS_STORAGE_NODE=1
      - GLOBAL_MESSAGE_TIMEOUT=600000
      - LOG_LEVEL=debug
      - MAX_IN_FLIGHT_RATIO=1
      - MAX_FAASLETS=20
      - MAX_FAASLETS_PER_FUNCTION=4
      - NETNS_MODE=off
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
      - worker-storage
    ports:
      - "8080:8080"

  cli:
    image: ${CLI_IMAGE}
    working_dir: /usr/local/code/faasm
    stdin_open: true
    tty: true
    privileged: true
    depends_on:
      - redis-queue
      - redis-state
    environment:
      - UPLOAD_HOST=${UPLOAD_HOST:-upload}
      - INVOKE_HOST=${INVOKE_HOST:-nginx}
      - LOG_LEVEL=info
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_STATE_HOST=redis-state
      - LD_LIBRARY_PATH=/build/faasm/third-party/lib:/usr/local/lib
    volumes:
      - .:/usr/local/code/faasm/
      - ./build/:/build/faasm/
      - ../faabric/include/faabric:/usr/local/faasm/native/include/faabric
      - ../faasm-toolchain/libfaasm/faasm.imports:/usr/local/faasm/llvm-sysroot/lib/wasm32-wasi/libfaasm.imports
      - ./container/machine-code/:/usr/local/faasm/object/
      - ./container/shared_store/:/usr/local/faasm/shared_store/
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
